// Car

export const FETCH_CARS_REQUEST = 'FETCH_CARS_REQUEST';

export const FETCH_CARS_SUCCESS = 'FETCH_CARS_SUCCESS';

export const FETCH_CARS_FAILURE = 'FETCH_CARS_FAILURE';

export const DELETE_CARS_REQUEST = 'DELETE_CARS_REQUEST';

export const DELETE_CARS_SUCCESS = 'DELETE_CARS_SUCCESS';

export const DELETE_CARS_FAILURE = 'DELETE_CARS_FAILURE';

