// Car detail

export const FETCH_CAR_DETAIL_REQUEST = 'FETCH_CAR_DETAIL_REQUEST';

export const FETCH_CAR_DETAIL_SUCCESS = 'FETCH_CAR_DETAIL_SUCCESS';

export const FETCH_CAR_DETAIL_FAILURE = 'FETCH_CAR_DETAIL_FAILURE';

export const SET_EDIT_MODE = 'SET_EDIT_MODE';

export const UPDATE_CAR_REQUEST = 'UPDATE_CAR_REQUEST';

export const UPDATE_CAR_SUCCESS = 'UPDATE_CAR_SUCCESS';

export const UPDATE_CAR_FAILURE = 'UPDATE_CAR_FAILURE';

export const UPDATE_BRAND_REQUEST = 'UPDATE_BRAND_REQUEST';

export const UPDATE_BRAND_SUCCESS = 'UPDATE_BRAND_SUCCESS';

export const UPDATE_BRAND_FAILURE = 'UPDATE_BRAND_FAILURE';